### ISSUE TITLE
Having troubled in installation.

### ISSUE THREAD

**Issue by iavsm** [AmirKamali/Flutter_Vnum#1]
import 'main.reflectable.dart';
import 'package:reflectable/reflectable.dart';
initializeReflectable();

Build.yaml:
```
targets:
  $default:
    builders:
      reflectable:
        generate_for:
          - lib/main.dart
          - test/**_widget_test.dart
        options:
          formatted: true

```
My project is not able to resolve this step.
